#!/usr/bin/env python3
"""Generate config.yaml for the LiteLLM proxy from .env.

One model group (`claude-main`) with one deployment per gateway key (up to 4).
LiteLLM's router spreads requests across the keys and retries on the next
key when one is rate-limited or errors — that's the rotation.

Usage:  python3 gen_config.py          # writes config.yaml next to this file
"""
import os
import secrets
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ENV_FILE = HERE / ".env"
OUT_FILE = HERE / "config.yaml"

MAX_KEYS = 8
MODEL_GROUP = "claude-main"


def load_env_file(path: Path) -> dict:
    """Minimal .env parser (KEY=VALUE lines, # comments, optional quotes)."""
    values = {}
    if not path.exists():
        return values
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if value:
            values[key] = value
    return values


def env(name: str, file_values: dict, default: str = "") -> str:
    """Process env wins over .env file (so you can override inline)."""
    return os.environ.get(name) or file_values.get(name) or default


def main() -> int:
    file_values = load_env_file(ENV_FILE)

    base_url = env("GATEWAY_BASE_URL", file_values, "https://llm.onerouter.pro")
    model = env("MAIN_MODEL", file_values, "qwen/qwen3.8-max-preview:free")

    keys = [
        env(f"GATEWAY_API_KEY_{i}", file_values) for i in range(1, MAX_KEYS + 1)
    ]
    keys = [k for k in keys if k]
    if not keys:
        print(
            "ERROR: no gateway keys found.\n"
            "  Copy .env.example to .env and set GATEWAY_API_KEY_1\n"
            "  (or run ./start.sh, which seeds it from your current "
            "ANTHROPIC_AUTH_TOKEN).",
            file=sys.stderr,
        )
        return 1

    master_key = env("LITELLM_MASTER_KEY", file_values)
    if not master_key:
        master_key = secrets.token_hex(32)
        print("NOTE: LITELLM_MASTER_KEY not set — generated one for this run.")

    lines = [
        "# AUTO-GENERATED by gen_config.py from .env — edit .env, not this file.",
        f"# Upstream: {base_url}  |  model: {model}  |  keys: {len(keys)}",
        "",
        "model_list:",
    ]
    for i, key in enumerate(keys, start=1):
        lines += [
            f"  - model_name: {MODEL_GROUP}          # key #{i}",
            "    litellm_params:",
            # anthropic provider → POST /v1/messages (gateway is Anthropic-only;
            # /chat/completions returns 405). extra_headers sends
            # `Authorization: Bearer`, which this gateway accepts (verified).
            f"      model: anthropic/{model}",
            f"      api_base: {base_url}",
            f"      api_key: {key}",
            f"      extra_headers: {{\"Authorization\": \"Bearer {key}\"}}",
            "      extra_body: {\"provider\": {\"service_tier\": \"standard\"}}  # forwarded to gateway",
        ]

    lines += [
        "",
        "router_settings:",
        "  routing_strategy: usage-based-routing-v2  # spread by rate-limit headroom",
        "  num_retries: 3                 # on 429/error, retry on the next key",
        "  retry_after: 30                # if all keys are saturated, wait 30s for a",
        "                                 # window to open instead of failing immediately",
        "  allowed_fails: 2               # cooldown a key after 2 fails/min",
        "  cooldown_time: 60",
        "",
        "litellm_settings:",
        "  drop_params: true              # don't 400 on params the gateway ignores",
        "  set_verbose: false",
        "  telemetry: false",
        "",
        "general_settings:",
        f"  master_key: {master_key}     # Bearer token Claude Code must send",
        "",
    ]

    OUT_FILE.write_text("\n".join(lines))
    print(f"Wrote {OUT_FILE} — {MODEL_GROUP} → {model} across {len(keys)} key(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
